title: i am Rahul
email: py.rahul16@gmail.com
description: “Our intelligence is what makes us human, and AI is an extension of that quality.” – Yann LeCun
author: Rahul
baseurl: ''
url: 'https://lRAHULl.github.io'

# Social Profiles
twitter_username: lRAHUL1l
github_username: lRAHULl
linkedin_username: lRAHULl

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
