title: I Am Rahul
email: rahulpadmaraju16@gmail.com
description: A Blog Theme by Start Bootstrap
author: Rahul
baseurl: ''
url: 'https://lRAHULl.github.io'

# Social Profiles
twitter_username: lRahul1l
github_username: lRAHULl
facebook_username: StartBootstrap

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
