title: I Am Rahul
email: rahulpadmaraju16@gmail.com
description: Artificial Intelligence is more of an Artist's thing than a Programmer's thing.
author: Rahul
baseurl: ''
url: 'https://lRAHULl.github.io'

# Social Profiles
twitter_username: lRAHUL1l
github_username: lRAHULl
linkedin_username: lRAHULl

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
